id: P010634
initial_creation_type: ocr
source_metadata:
  id: bdr:W20113
  title: སྟོན་བཤད་སྐྱིད་གཡང་དགའ་འཁྱིལ
  author: ''
  volumes:
    0e1863e0d11a491ca5158338523f34b5:
      image_group_id: I4760
      title: ''
      volume_number: 1
      total_pages: 270
